# Numpy

Create a NumPy array of numbers from 1 to 20 and extract all even numbers.

In [2]:
import numpy as np

np.arange(0,21,2) 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [7]:
num = np.arange(0,21)
even = num[num%2==0]
even

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

Generate a 3x3 NumPy array of random integers between 10 and 50. Find the maximum and minimum values

In [15]:
np.random.randint(10,51,(3,3))

array([[19, 45, 27],
       [45, 23, 15],
       [32, 44, 36]], dtype=int32)

Create a 3×3 matrix with values from 1 to 9 using np.arange() and reshape.

In [17]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Generate a 4×4 matrix of random integers between 10 and 50.

In [18]:
np.random.randint(10,51,(4,4))

array([[17, 47, 32, 29],
       [33, 14, 42, 22],
       [16, 35, 22, 31],
       [40, 45, 24, 20]], dtype=int32)

From the array [10, 20, 30, 40, 50], extract:

the first element

the last element

the middle three elements

In [19]:
arr = np.array([10,20,30,40,50])
print(arr[0])
print(arr[-1])
print(arr[1:-1])

10
50
[20 30 40]


From the matrix
[[ 5, 10, 15],
 [20, 25, 30],
 [35, 40, 45]]

select:

the element in row 2, column 3

the entire second row

the entire third column

In [30]:
mat = np.array([[ 5, 10, 15],
 [20, 25, 30],
 [35, 40, 45]]
)

print(mat[1][2])
print(mat[1])
print(mat[:,2])

30
[20 25 30]
[15 30 45]


Create an array of even numbers between 0 and 50.
Then create another array of odd numbers between 0 and 50.

In [35]:
even = np.arange(0,51,2)
odd = np.arange(1,50,2)
print(even)
print(odd)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]


Make a 5×5 matrix filled with ones, and replace the diagonal with zeros.

In [43]:
matrix =np.ones((5,5))
np.fill_diagonal(matrix,0)
matrix

array([[0., 1., 1., 1., 1.],
       [1., 0., 1., 1., 1.],
       [1., 1., 0., 1., 1.],
       [1., 1., 1., 0., 1.],
       [1., 1., 1., 1., 0.]])

Create a 3×3 random float matrix (values between 0 and 1).
Find the maximum, minimum, and mean values.

In [9]:
mat = np.random.rand(3,3)

print(np.min(mat))
print(np.max(mat))
print(np.mean(mat))

0.08951225223515802
0.9605287241303565
0.5188732230664068


Create a 2×5 matrix using np.linspace() to generate 10 numbers between 0 and 1.

In [13]:
m = np.linspace(0,1,10).reshape(2,5)
m

array([[0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444],
       [0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ]])

Given an array of numbers from 1 to 30, extract only those numbers which are divisible by 3 and 5.

In [22]:
arr = np.arange(1,31)
divBy3 = arr[arr % 3 == 0]
divBy5 = arr[arr % 5 == 0]
divBy3and5 = arr[(arr % 3 == 0) &(arr % 5 == 0)]
print(divBy3)
print(divBy5)
print(divBy3and5)

[ 3  6  9 12 15 18 21 24 27 30]
[ 5 10 15 20 25 30]
[15 30]


# 📝 NumPy Intermediate Questions

Create a 4×4 matrix of random integers between 1 and 50.

Find the mean of each column.

Find the mean of each row.

In [36]:
mat = np.random.randint(1,51,(4,4))
c = 0
r = 0
for i in range(4):
    print(f"mean of Col {c+1} : {np.mean(mat[:,c])}")
    print(f"mean of Row {r+1} : {np.mean(mat[r])} ")
    c = c+1
    r = r+1

mean of Col 1 : 23.25
mean of Row 1 : 24.25 
mean of Col 2 : 24.75
mean of Row 2 : 26.75 
mean of Col 3 : 28.25
mean of Row 3 : 32.0 
mean of Col 4 : 30.25
mean of Row 4 : 23.5 


In [ ]:
mat = np.random.randint(1,51,(4,4))

col = np.mean(mat,axis=0)
row = np.mean(mat,axis=1)
print(f"Mean of colums: {col}")
print(f"mean of Rows : {row}")

Mean of colums: [28.75 21.   12.25 19.75]
mean of Rows : [26.75 19.5   5.25 30.25]


Given the matrix
[[10, 20, 30],
 [40, 50, 60],
 [70, 80, 90]]

Extract the sum of the 2nd column.
Extract the mean of the 3rd row.

In [40]:
mat = np.array([[10, 20, 30],
 [40, 50, 60],
 [70, 80, 90]]
)
print(np.sum(mat[:,1]))
print(np.mean(mat[2]))

150
80.0


Create a 5×5 random integer matrix (values between 1 and 100).

Find all elements greater than 50.

Replace all elements less than 20 with 0.

In [51]:
mat = np.random.randint(1,101,(5,5))
g50 = mat[mat > 50]

mat[mat < 20] = 0
mat

array([[80, 66, 39, 63, 27],
       [44,  0, 99, 59, 39],
       [20, 21, 95,  0, 65],
       [ 0, 59,  0, 30, 81],
       [54,  0, 99,  0, 99]], dtype=int32)

Generate a 6×6 matrix with values from 1 to 36.

Extract the main diagonal.

Extract the secondary diagonal (top-right → bottom-left).

Find the sum of both diagonals.

In [ ]:
mat = np.arange(1,37).reshape(6,6)
main = np.diag(mat)
secondary = np.diag(np.fliplr(mat))
print(f"Sum of main diagonal : {np.sum(main)}\nSum of the seconday diagonal : {np.sum(secondary)}")

[ 1  8 15 22 29 36]
[ 6 11 16 21 26 31]
Sum of main diagonal : 111
Sum of the seconday diagonal : 111


Create a 3×5 random integer matrix (1–30).

Find the maximum value of each column.

Find the minimum value of each row.

Find the index (row, col) of the overall maximum value.

In [64]:
mat = np.random.randint(1,31,(3,5))

print(np.max(mat,axis=0))
print(np.min(mat,axis=1))
i = np.max(mat)
print(np.where(mat == i))

[30 29 20 21 30]
[ 9 11 11]
(array([1, 2]), array([4, 0]))


# Array properties
ndim,shape,itemsize,nbytes,Transpose

In [71]:
mat = np.array([[10, 20, 30],
 [40, 50, 60],
 [70, 80, 90]])

print(np.ndim(mat))
print(np.shape(mat))
print(mat.itemsize)
print(mat.nbytes)
print(mat)
print(mat.T)

2
(3, 3)
8
72
[[10 20 30]
 [40 50 60]
 [70 80 90]]
[[10 40 70]
 [20 50 80]
 [30 60 90]]


# Slicing

In [73]:
arr = np.arange(1,11)

print(arr[1:5:2])

[2 4]


In [ ]:
mat = np.array([[10, 20, 30],
 [40, 50, 60],
 [70, 80, 90]])

